#!/usr/bin/env node

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import yaml from "js-yaml";

import { loadConfig } from "./lib/config.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..", "..");

export function buildLabelerYaml(config) {
  // actions/labeler@v5 expects: { "label-name": [{ "changed-files": [{ "any-glob-to-any-file": [paths] }] }] }
  // Aggregate by label across all path_mappings.
  const byLabel = new Map();

  for (const mapping of config.path_mappings ?? []) {
    for (const label of mapping.labels ?? []) {
      if (!byLabel.has(label)) {
        byLabel.set(label, []);
      }
      byLabel.get(label).push(...mapping.paths);
    }
  }

  const out = {};
  // Sort labels for determinism
  for (const label of [...byLabel.keys()].sort()) {
    const paths = [...new Set(byLabel.get(label))].sort();
    out[label] = [{ "changed-files": [{ "any-glob-to-any-file": paths }] }];
  }

  const header = [
    "# This file is GENERATED by scripts/pipeline/generate-labeler.mjs.",
    "# Do not edit by hand. Edit .github/pipeline-config.yml and run `make pipeline-generate`.",
    "# Format: actions/labeler@v5 (see https://github.com/actions/labeler).",
    "",
  ].join("\n");

  return header + yaml.dump(out, { lineWidth: 120, noRefs: true });
}

if (process.argv[1]?.endsWith("/generate-labeler.mjs")) {
  const configPath = process.argv[2] || join(REPO_ROOT, ".github", "pipeline-config.yml");
  const outPath = process.argv[3] || join(REPO_ROOT, ".github", "labeler.yml");
  const config = loadConfig(configPath);
  const content = buildLabelerYaml(config);
  writeFileSync(outPath, content);
  console.log(`Wrote ${outPath}`);
}
