#!/usr/bin/env node

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import yaml from "js-yaml";
import { createHash } from "node:crypto";

import { loadConfig } from "./lib/config.mjs";
import { universalLabels } from "./lib/universal-labels.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..", "..");

function hashColor(name) {
  // Deterministic 6-char hex color from name; not cryptographic.
  const hash = createHash("sha1").update(name).digest("hex");
  // Use first 6 hex chars but bias to mid-saturation by setting bit floor.
  const r = Math.max(parseInt(hash.slice(0, 2), 16), 0x60).toString(16).padStart(2, "0");
  const g = Math.max(parseInt(hash.slice(2, 4), 16), 0x60).toString(16).padStart(2, "0");
  const b = Math.max(parseInt(hash.slice(4, 6), 16), 0x60).toString(16).padStart(2, "0");
  return `${r}${g}${b}`;
}

function compareLabels(a, b) {
  return a.name.localeCompare(b.name);
}

export function buildLabelsYaml(config) {
  const labels = [...universalLabels];

  for (const domain of config.domains ?? []) {
    labels.push({
      name: `domain:${domain.name}`,
      color: hashColor(`domain:${domain.name}`),
      description: domain.description || `Domain: ${domain.name}`,
    });
  }

  for (const component of config.components ?? []) {
    labels.push({
      name: `component:${component.name}`,
      color: hashColor(`component:${component.name}`),
      description: component.description || `Component: ${component.name}`,
    });
  }

  labels.sort(compareLabels);

  const header = [
    "# This file is GENERATED by scripts/pipeline/generate-labels.mjs.",
    "# Do not edit by hand. Edit .github/pipeline-config.yml and run `make pipeline-generate`.",
    "",
  ].join("\n");

  return header + yaml.dump(labels, { lineWidth: 120, noRefs: true });
}

if (process.argv[1]?.endsWith("/generate-labels.mjs")) {
  const configPath = process.argv[2] || join(REPO_ROOT, ".github", "pipeline-config.yml");
  const outPath = process.argv[3] || join(REPO_ROOT, ".github", "labels.yml");
  const config = loadConfig(configPath);
  const content = buildLabelsYaml(config);
  writeFileSync(outPath, content);
  console.log(`Wrote ${outPath} (${content.split("\n").length} lines)`);
}
