#!/usr/bin/env node

// scripts/install.mjs
//
// One-shot installer that wires Pipeline Core into a consumer repo. Copies
// caller workflows, drops a starter pipeline-config.yml, seeds the
// ISSUE_TEMPLATE config, and optionally opens a "chore(install): pipeline-core"
// PR via gh.
//
// Designed for two flows:
//
//   1. Manual:   node /path/to/pipeline-core/scripts/install.mjs --repo .
//   2. Auto-PR: node /path/to/pipeline-core/scripts/install.mjs --repo . --auto-pr
//
// The installer never edits an existing `pipeline-config.yml` — re-runs against
// an already-installed repo bail with a clear message. To uninstall, delete the
// files by hand; this script is install-only by design.

import { existsSync, readFileSync, writeFileSync, mkdirSync, readdirSync, copyFileSync } from "node:fs";
import { dirname, join, basename } from "node:path";
import { fileURLToPath } from "node:url";
import { execSync, spawnSync } from "node:child_process";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PIPELINE_CORE_ROOT = join(__dirname, "..");
const CALLER_TEMPLATES_DIR = join(PIPELINE_CORE_ROOT, "templates", "caller-workflows");
const ISSUE_TEMPLATE_DIR = join(PIPELINE_CORE_ROOT, "templates", "ISSUE_TEMPLATE");
const CONFIG_EXAMPLE = join(PIPELINE_CORE_ROOT, "templates", "pipeline-config.yml.example");

// ─── Pure logic (testable without filesystem side effects on real repos) ────

export function renderStarterConfig({ exampleText, installationId, cronTimezone }) {
  let out = exampleText;
  if (installationId) {
    out = out.replace(
      /installation_id:\s*\S+(\s*#.*)?/,
      (_, comment) => `installation_id: ${installationId}${comment ?? ""}`,
    );
  }
  if (cronTimezone) {
    out = out.replace(
      /cron_timezone:\s*\S+(\s*#.*)?/,
      (_, comment) => `cron_timezone: ${cronTimezone}${comment ?? ""}`,
    );
  }
  return out;
}

export function deriveInstallationId(repoPath) {
  // Lowercase, replace non-[a-z0-9-] with hyphen, trim hyphens. Schema requires
  // 2-64 chars matching [a-z0-9-]. We deliberately do NOT strip extensions
  // because folder names like "Catnets.com.au" are legitimate repo names where
  // the trailing ".au" is meaningful, not a file extension.
  const raw = basename(repoPath)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  if (raw.length < 2) return `${raw}-repo`.slice(0, 64);
  return raw.slice(0, 64);
}

export function planInstall({ repoDir, callerTemplatesDir = CALLER_TEMPLATES_DIR, issueTemplateDir = ISSUE_TEMPLATE_DIR }) {
  // Returns the list of {src, dest, kind} the installer will create. Doesn't
  // touch disk. Refuses (returns { conflict: ... }) if any file already exists,
  // so the caller can bail before any mutation.
  const ops = [];

  const configPath = join(repoDir, ".github", "pipeline-config.yml");
  if (existsSync(configPath)) {
    return { conflict: `.github/pipeline-config.yml already exists at ${configPath}` };
  }
  ops.push({ src: CONFIG_EXAMPLE, dest: configPath, kind: "config", render: true });

  for (const f of readdirSync(callerTemplatesDir)) {
    if (!f.endsWith(".yml") && !f.endsWith(".yaml")) continue;
    const dest = join(repoDir, ".github", "workflows", f);
    if (existsSync(dest)) {
      return { conflict: `.github/workflows/${f} already exists; refusing to overwrite` };
    }
    ops.push({ src: join(callerTemplatesDir, f), dest, kind: "caller" });
  }

  // ISSUE_TEMPLATE/config.yml is the only one we copy at install time. The
  // body templates (bug/improvement/spike/experiment) are generated by
  // `make pipeline-generate` AFTER the consumer fills out their config.
  const issueConfigSrc = join(issueTemplateDir, "config.yml");
  if (existsSync(issueConfigSrc)) {
    const dest = join(repoDir, ".github", "ISSUE_TEMPLATE", "config.yml");
    if (existsSync(dest)) {
      return { conflict: `.github/ISSUE_TEMPLATE/config.yml already exists` };
    }
    ops.push({ src: issueConfigSrc, dest, kind: "issue-config" });
  }

  return { ok: true, ops };
}

// ─── Filesystem application ─────────────────────────────────────────────────

export function applyInstall({ ops, installationId, cronTimezone }) {
  const written = [];
  for (const op of ops) {
    mkdirSync(dirname(op.dest), { recursive: true });
    if (op.render) {
      const exampleText = readFileSync(op.src, "utf8");
      writeFileSync(op.dest, renderStarterConfig({ exampleText, installationId, cronTimezone }));
    } else {
      copyFileSync(op.src, op.dest);
    }
    written.push(op.dest);
  }
  return written;
}

// ─── Git/PR side effects (real-repo only) ───────────────────────────────────

function run(cmd, args, opts = {}) {
  const r = spawnSync(cmd, args, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"], ...opts });
  if (r.status !== 0) {
    const err = new Error(`${cmd} ${args.join(" ")} exited ${r.status}: ${r.stderr || r.stdout}`);
    err.stderr = r.stderr;
    err.stdout = r.stdout;
    err.status = r.status;
    throw err;
  }
  return r.stdout.trim();
}

function openAutoPR({ repoDir, branch, written, upstreamMajor }) {
  // Sanity check: cwd must be a git repo with a remote.
  run("git", ["-C", repoDir, "rev-parse", "--show-toplevel"]);
  const remoteUrl = run("git", ["-C", repoDir, "remote", "get-url", "origin"]);

  run("git", ["-C", repoDir, "checkout", "-b", branch]);
  run("git", ["-C", repoDir, "add", ...written.map((p) => p.startsWith(repoDir) ? p.slice(repoDir.length + 1) : p)]);
  run("git", ["-C", repoDir, "commit", "-m", "chore(pipeline-core): install reusable pipeline\n\nGenerated by `pipeline-core/scripts/install.mjs`."]);
  run("git", ["-C", repoDir, "push", "-u", "origin", branch]);

  const body = `## Summary

Wires Pipeline Core into this repo. Callers pin to \`leebaroneau/pipeline-core@${upstreamMajor}\` — they pick up upstream fixes automatically.

## What this adds

- \`.github/pipeline-config.yml\` — starter config; **edit before merge** to set the right domains, components, path mappings, and reviewer policy.
- \`.github/workflows/pipeline-*.yml\` — caller workflows that delegate to pipeline-core's reusable workflows.
- \`.github/ISSUE_TEMPLATE/config.yml\` — disables blank issues so contributors pick a structured template.

## After merge

1. \`gh workflow run pipeline-validate-config.yml\` — validates the config against the schema.
2. \`gh workflow run pipeline-labels-sync.yml\` — creates the 47 universal labels + your declared domain/component labels.
3. Generated artifacts (\`.github/labels.yml\`, \`.github/labeler.yml\`, \`.github/ISSUE_TEMPLATE/*.yml\`) are emitted by \`make pipeline-generate\` once you have the pipeline-core checkout handy; the drift-scan workflow will hard-fail until they're committed.

## Generated by

\`pipeline-core@${upstreamMajor}\` install script.
`;

  // Best-effort PR creation; if gh is missing or auth fails, surface clearly.
  try {
    run("gh", ["pr", "create", "--title", "chore(pipeline-core): install reusable pipeline", "--body", body], { cwd: repoDir });
  } catch (err) {
    process.stderr.write(`Branch pushed, but \`gh pr create\` failed: ${err.message}\n`);
    process.stderr.write("Open the PR manually with the link shown by the push above.\n");
    return null;
  }
  return run("gh", ["pr", "view", "--json", "url", "--jq", ".url"], { cwd: repoDir });
}

// ─── CLI entry ──────────────────────────────────────────────────────────────

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--repo") args.repoDir = argv[++i];
    else if (a === "--installation-id") args.installationId = argv[++i];
    else if (a === "--cron-timezone") args.cronTimezone = argv[++i];
    else if (a === "--branch") args.branch = argv[++i];
    else if (a === "--upstream-major") args.upstreamMajor = argv[++i];
    else if (a === "--auto-pr") args.autoPR = true;
    else if (a === "--help" || a === "-h") args.help = true;
  }
  return args;
}

const HELP = `Usage: install.mjs [options]

Installs Pipeline Core caller workflows + starter config into a consumer repo.
Idempotent: refuses to overwrite an existing pipeline-config.yml or workflow.

Options:
  --repo <dir>             Consumer repo root (default: cwd)
  --installation-id <slug> deployment.installation_id (default: derived from repo dir name)
  --cron-timezone <tz>     deployment.cron_timezone (default: keep the example's)
  --branch <name>          Branch to commit on with --auto-pr (default: chore/install-pipeline-core)
  --upstream-major <ref>   Major to pin callers to (default: v1)
  --auto-pr                Create branch, commit, push, and open a PR via gh
  --help, -h               Show this help

Exit code: 0 on success, 1 on conflict (already installed) or error.
`;

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    process.stdout.write(HELP);
    return 0;
  }
  const repoDir = args.repoDir ?? process.cwd();
  const installationId = args.installationId ?? deriveInstallationId(repoDir);
  const branch = args.branch ?? "chore/install-pipeline-core";
  const upstreamMajor = args.upstreamMajor ?? "v1";

  const plan = planInstall({ repoDir });
  if (plan.conflict) {
    process.stderr.write(`Refusing to install: ${plan.conflict}\n`);
    return 1;
  }

  const written = applyInstall({ ops: plan.ops, installationId, cronTimezone: args.cronTimezone });
  process.stdout.write(`Installed Pipeline Core scaffolding (${written.length} files) under ${repoDir}\n`);
  for (const p of written) process.stdout.write(`  ${p.startsWith(repoDir) ? p.slice(repoDir.length + 1) : p}\n`);

  if (args.autoPR) {
    const url = openAutoPR({ repoDir, branch, written, upstreamMajor });
    if (url) process.stdout.write(`\nPR: ${url}\n`);
  } else {
    process.stdout.write([
      "",
      "Next steps (review and commit):",
      `  1. Edit .github/pipeline-config.yml — set installation_id (now: ${installationId}), domains, components, path_mappings.`,
      "  2. Run `make pipeline-generate` from a pipeline-core checkout to regenerate labels.yml/labeler.yml/ISSUE_TEMPLATE/*.",
      "  3. Open a PR with these changes; after merge, run `gh workflow run pipeline-labels-sync.yml` to create the labels.",
      "  4. `make pipeline-doctor REPO=.` from a pipeline-core checkout to verify health.",
      "",
    ].join("\n"));
  }
  return 0;
}

if (import.meta.url === `file://${process.argv[1]}` || process.argv[1]?.endsWith("/install.mjs")) {
  main().then((code) => process.exit(code)).catch((err) => {
    process.stderr.write(`install.mjs failed: ${err.stack ?? err.message ?? err}\n`);
    process.exit(1);
  });
}
